# File: .github/workflows/repo-sync.yml
name: dust
on:
  schedule:
    - cron: '1 3,15 * * *'
  workflow_dispatch:
  watch:
    types: started
  push:
    branches: [ master ]
  repository_dispatch:
    types: dust
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync dust
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://share.r2ray.com/dust"
          source_branch: "master"
          destination_branch: "3"
          github_token: ${{ github.event.client_payload.PAT || secrets.PAT }}
