# File: .github/workflows/repo-sync.yml
name: jd_study
on:
  schedule:
    - cron: '12 15 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: jd_study
jobs:
  repo-sync:
    env:
      PAT: ${{ github.event.client_payload.PAT || secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
      dst_key: ${{ secrets.GITEE_PRIVATE_KEY }} # 我自己同步到gitee使用，其他人可忽略
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: 开始自动同步
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://bitbucket.org/jd-study/jd_scripts.git"
          source_branch: "maste"
          destination_branch: "jd_scripts"
          github_token: ${{ github.event.client_payload.PAT || secrets.PAT }}
